apiVersion: apps/v1
kind: Deployment
metadata:
  name: medilab-app-deployment
  namespace: medilab-db-ns
spec:
  selector:
    matchLabels:
      app: medilab-app-react
  replicas: 1
  template:
    metadata:
      labels:
        app: medilab-app-react
    spec:
      containers:
        - name: medilab-app-deployment
          image: ashokit/medilab-ui
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              #value: medilab-app-schema
              valueFrom:
                configMapKeyRef:
                  key: MEDILAB_DB_SCHEMA_NAME
                  name: medilab-config-map
            #- name: MYSQL_USER
             # value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: medilab-app-react-svc
  namespace: medilab-db-ns
spec:
  selector:
    app: medilab-app-react
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      nodePort: 30785
  type: NodePort # type of the service.
